# Generated by Django 3.1 on 2020-08-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS_CBV_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todos',
            new_name='todo',
        ),
    ]
